import bcrypt from 'bcryptjs'
const data = {
  users: [
    {
      name: 'harsh',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'john',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      // _id: '1',
      name: 'Paris Saint-Germain 2022/23',
      slug: 'nike-slim-shirt',
      category: 'shirts',
      image: '/images/p1.jpg',
      price: 110,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.8,
      numReviews: 10,
      description: 'Men/s Nike Dri-FIT ADV Football Shirt.',
    },
    {
      // _id: '2',
      name: 'Nike Dri-FIT',
      slug: 'nike-dri-fit',
      category: 'shirts',
      image: '/images/p2.jpg',
      price: 50,
      countInStock: 6,
      brand: 'Nike',
      rating: 4.4,
      numReviews: 18,
      description: 'Men/s Sleeveless Hooded Pullover Training Top.',
    },
    {
      // _id: '3',
      name: 'Giannis',
      slug: 'nike-slim-pants',
      category: 'pants',
      image: '/images/p3.jpg',
      price: 60,
      countInStock: 12,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 11,
      description: 'Men/s Lightweight Basketball Trousers.',
    },
    {
      // _id: '4',
      name: 'SL Single Jersey to Pants',
      slug: 'addidas-slim-pants',
      category: 'pants',
      image: '/images/p4.jpg',
      price: 78,
      countInStock: 10,
      brand: 'Addidas',
      rating: 4.3,
      numReviews: 10,
      description:
        'Cotton workout pants that keep you comfortable through your training sessions.',
    },
  ],
}
export default data
